### ISSUE TITLE
How feasible is STDIN?

### ISSUE THREAD

**Issue by shyshy** [mnutt/khepri#5]
Is it possible for the process manager to receive STDIN? Is it purely a logging / output service?

Wondering if it's investigation to setup usecases like `binding.pry` with the Rails server.

Unrelated, was also running into a weird issue with trying to exit the Rails server process after having stopped on a breakpoint. I'll post when I eventually can reproduce reliably.

**Comment by mnutt** [comment]
It seems pretty feasible, actually. We'd just need to capture all keyboard input while the log is focused and pass it through RPC to stdin for the app.

It sounds like the bug may be related to us not successfully force-killing a process when it doesn't respond to SIGTERM. (which I'll bet a rails process stuck in binding.pry doesn't)
